#!/bin/bash

# Fail if any sub-command fails
set -e

source /opt/ros/$ROS_DISTRO/setup.bash

# Install documentation dependencies if not already available
! rosdoc_lite --help > /dev/null && sudo apt-get install -y ros-$ROS_DISTRO-rosdoc-lite
! doxygen -v > /dev/null && sudo apt-get install -y doxygen
! sphinx-build --version > /dev/null && sudo apt-get install python3-sphinx

# Set up environment
mkdir -p ~/autonomous-twizy/docs
cd ~/autonomous-twizy/docs

# Clear out docs directory
find "." ! -path "." ! -path "./.git/*" ! -path "./.git" ! -path "./.nojekyll" ! -path "./README.md" -exec rm -rf {} +

commit_hash=`git -C ../src log -n 1 --pretty=format:"%H"`
commit_message=`git -C ../src log -n 1 --pretty=format:"%s"`

# Fetch stylesheet along with its licence from online source
curl https://raw.githubusercontent.com/sindresorhus/github-markdown-css/main/license | awk '{print "// " $0}' > index.css
echo -e "\n\n" >> index.css
curl https://raw.githubusercontent.com/sindresorhus/github-markdown-css/main/github-markdown.css >> index.css


echo "\
<html>
<head>
<title>Autonomous-Twizy Code API</title>
<link type='text/css' rel='stylesheet' href='index.css' />
<meta charset='UTF-8'>
</head>
<body>
<div class='markdown-body' />

<h1>Autonomous-Twizy Code API</h1>

<p>
The documentation listed here has been automatically generated by a script running <a href='http://wiki.ros.org/rosdoc_lite'>rosdoc_lite</a> on packages present in the repo which contains the file <code>rosdoc.yaml</code> in their root directory.
<b>rosdoc_lite generates only code API docs</b> (for classes, methods etc.), not ROS API docs (topics, parameters etc.).
Packages not included in the below list do not intend to expose any externally usable API.
</p>

<p>For ROS API docs please see READMEs in the root folder of each package.</p>

<p>For information on internal code functionality, please see comments in the source code.</p>

<h2>Documented ROS Packages</h2>

<p>
<ul>" > index.html

for pkg in ../src/*; do
	# Skip entries which do not declare rosdoc_lite settings
	if [ ! -f "$pkg/rosdoc.yaml" ]; then
		continue
	fi
	
	# Build documentation for a single package
	name=`basename $pkg`
	rosdoc_lite -o "$name" "$pkg"
	
	# Add package entry to index.md
	echo "<li><a href='$name/html'>$name</a></li>" >> index.html
done

echo "\
</ul>
</p>

<hr>

<small>The latest commit included in this documentation is <a href='https://github.com/OssianEriksson/autonomous-twizy/tree/$commit_hash'>$commit_message</a></small>

</div>
</body>
</html>
" >> index.html

if [[ -z "${GITHUB_ACTION}" ]]; then # If running on a local computer
	docs_abspath=`pwd`
	echo -e "\n\nThe code API documentation has been built to $docs_abspath"
	echo -e "\nYou can view the documentation in your browser, e.g. using firefox:"
	echo -e "\n    firefox $docs_abspath/index.html\n"
fi
