#!/usr/bin/python3

import rospy
from ackermann_msgs.msg import AckermannDriveStamped
from geometry_msgs.msg import Twist


from math import atan


def convert_trans_rot_vel_to_steering_angle(v, omega, wheelbase):
    if omega == 0 or v == 0:
        return 0

    radius = v / omega
    return atan(wheelbase / radius)


def main():
    # Initialize ROS node
    rospy.init_node('converter')

    # Read parameters from ROS parameter server
    max_steering_angle = rospy.get_param('~max_steering_angle')
    wheelbase = rospy.get_param('~wheelbase')
    frame_id = rospy.get_param('~frame_id', 'odom')

    def cmd_callback(data):

        v = data.linear.x
        steering = convert_trans_rot_vel_to_steering_angle(
            v, data.angular.z, wheelbase)

        msg = AckermannDriveStamped()
        msg.header.stamp = rospy.Time.now()
        msg.header.frame_id = frame_id
        msg.drive.steering_angle = min(
            max(steering, -max_steering_angle), max_steering_angle)
        msg.drive.speed = v

        pub.publish(msg)

    rospy.Subscriber('cmd_vel', Twist, cmd_callback, queue_size=1)
    pub = rospy.Publisher('ackermann_cmd', AckermannDriveStamped, queue_size=1)

    try:
        rospy.spin()

    except rospy.ROSInterruptException:
        pass


if __name__ == '__main__':
    main()
