transform_tolerance: 1.0

inflater_layer:
  inflation_radius: 1.05 # Random number, very important!

obstacle_layer:
  obstacle_range: 8.5
  raytrace_range: 9.0
  max_obstacle_height: 2.0

  observation_sources: front_point_cloud_sensor

  front_point_cloud_sensor: 
    sensor_frame: front_realsense
    data_type: PointCloud2
    topic: /camera/front/depth/color/points
    min_obstacle_height: 0.3
    marking: true
    clearing: true