frequency: 10
base_link: 'base_link'

sensors:
- topic: /gnss/left/fix
  type: sensor_msgs/NavSatFix
  static_position: True

- topic: /gnss/right/fix
  type: sensor_msgs/NavSatFix
  static_position: True