frequency: 30
base_link: 'base_link'
x_max:
- [.inf]
- [.inf]
- [.inf]
- [2.0]
- [5.0]
- [0.0]
- [0.0]
- [10.0]
- [0.0]
- [0.0]
- [0.5]

sensors:
- topic: /gnss/left/fix
  type: sensor_msgs/NavSatFix
  static_position: True

- topic: /gnss/right/fix
  type: sensor_msgs/NavSatFix
  static_position: True