global_costmap:
  plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}

  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  rolling_window: true
  width: 500.0
  height: 500.0
  resolution: 20.0
  