#!/usr/bin/python3

import rospy

import sys
import select
import termios
import tty
from math import degrees

from ackermann_msgs.msg import AckermannDriveStamped

controls = {
    'forward': '\x41',  # Up arrow
    'reverse': '\x42',  # Down arrow
    'left': '\x44',     # Left arrow
    'right': '\x43'     # Right arrow
}

special = {
    'exit': '\x03',  # Ctrl-C
    'reset': '\x20'  # Space
}


def main():
    rospy.init_node('key_teleop')

    max_forward_speed = rospy.get_param('~max_forward_speed')
    max_reverse_speed = rospy.get_param('~max_reverse_speed')
    max_steering_angle = rospy.get_param('~max_steering_angle')

    fr, lr = 0, 0

    msg = AckermannDriveStamped()

    pub = rospy.Publisher('ackermann_cmd', AckermannDriveStamped, queue_size=1)

    print('**********************************************************')
    print('* - Toggle forward, reverse and steering with arrow keys *')
    print('* - Reset all controls to zero by hitting space          *')
    print('* - Press Ctrl+C to exit                                 *')
    print('**********************************************************')

    while not rospy.is_shutdown():
        old_attr = termios.tcgetattr(sys.stdin)
        char = None
        try:
            tty.setraw(sys.stdin.fileno())
            char = sys.stdin.read(1)
        finally:
            termios.tcsetattr(sys.stdin, termios.TCSADRAIN, old_attr)

        if char in controls.values() or char in special.values():
            if char == controls['forward']:
                fr = 1 if fr == -1 else (1 - fr)
            if char == controls['reverse']:
                fr = -1 if fr == 1 else (-1 - fr)
            if char == controls['left']:
                lr = 1 if lr == -1 else (1 - lr)
            if char == controls['right']:
                lr = -1 if lr == 1 else (-1 - lr)
            elif char == special['reset'] or char == special['exit']:
                fr, lr = 0, 0

            angle = lr * max_steering_angle
            speed = fr * (max_forward_speed if fr > 0 else max_reverse_speed)

            msg.header.stamp = rospy.Time.now()
            msg.drive.steering_angle = angle
            msg.drive.speed = speed

            pub.publish(msg)

            print(f'speed: {speed:6.2f} m/s, '
                  f'steering angle: {degrees(angle):6.2f}°')

            if char == special['exit']:
                break


if __name__ == '__main__':
    main()
