# Additional attributes of the twizy used to generate models of the car in
# various formats. This file should NOT be loaded as ROS parameters with e.g.
# the <rosparam> tag since the information can be accessed in other ways,
# for example as included in messages a ROS node can subscribe to


left_piksi_gnss:
  position:  # In chassis frame: x forward z up, (0, 0, 0) centered on chassis floor 
    x: 0.058
    y: 0.325
    z: 1.41
  accuracy: 0.03  # Standard deviation


right_piksi_gnss:
  position:  # In chassis frame: x forward z up, (0, 0, 0) centered on chassis floor 
    x: 0.058
    y: -0.345
    z: 1.41
  accuracy: 0.03  # Standard deviation


left_piksi_imu:
  position:  # In chassis frame: x forward z up, (0, 0, 0) centered on chassis floor 
    x: -0.843
    y: -0.05
    z: 1.05
  rotation:  # Axis angle in chassis frame
    x: 0.02674506
    y: 0.99953344
    z: -0.01475112
    angle: 3.09830016  # Imu forward originally facing towards x in chassis frame
  accelerometer_accuracy: 0.2  # Standard deviation (m/s^2)
  gyro_accuracy: 0.05  # Standard deviation (rad/s)


right_piksi_imu:
  position:  # In chassis frame: x forward z up, (0, 0, 0) centered on chassis floor 
    x: -0.843
    y: -0.05
    z: 0.95
  rotation:  # Axis angle in chassis frame
    x: 0.01836127
    y: 0.99983031
    z: 0.00149044
    angle: 3.09397341  # Imu forward originally facing towards x in chassis frame
  accelerometer_accuracy: 0.2  # Standard deviation (m/s^2)
  gyro_accuracy: 0.05  # Standard deviation (rad/s)


front_realsense:
  position:  # In chassis frame: x forward z up, (0, 0, 0) centered on chassis floor 
    x: 0.068
    y: 0.0
    z: 1.375
  rotation:  # Axis angle in chassis frame
    x: 0.0
    y: 1.0
    z: 0.0
    angle: 0.0  # Camera originally looking at x in chassis frame
  color:
    fov: 1.117010721276371  # Horizontal FOV (64°)
    width: 640
    height: 480
  depth:
    max_range: 10.0


rear_realsense:
  position:  # In chassis frame: x forward z up, (0, 0, 0) centered on chassis floor 
    x: -1.133
    y: 0.0
    z: 0.68
  rotation:  # Axis angle in chassis frame
    x: 0.0
    y: 0.0
    z: 1.0
    angle: 3.141592653589793  # Camera originally looking at x in chassis frame
  color:
    fov: 1.117010721276371  # Horizontal FOV (64°)
    width: 640
    height: 480
  depth:
    max_range: 10.0


lidar_vlp16:
  position:  # In chassis frame: x forward z up, (0, 0, 0) centered on chassis floor 
    x: 0.0
    y: 0.0
    z: 1.423
  rotation:  # Axis angle in chassis frame
    x: 0.0
    y: 1.0
    z: 0.0
    angle: 0.0  # Camera originally looking at x in chassis frame
  max_range: 100              # 100 meter
  vertical_fov: 0.523598776   # 30 grader
  fov: 6.28318530718          # 360 grader / 2*pi
  frequency: 20               # 20 Hz
  number_of_layers: 12        #
  horizontal_resolution: 180  # 360/2 = 180


left_wheel_encoder:
  noise: 0.01  # Standard deviation (rad)


right_wheel_encoder:
  noise: 0.01  # Standard deviation (rad)